languageCode = "en-us"
theme = "hugo-docs"
canonifyURLs = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "home"
  weight = -1

[[menu.main]]
  name = "Getting Started"
  url = "/get-started/"
  identifier = "get-started"
  weight = 1
[[menu.main]]
  name = "Resources"
  url = "/resources/"
  identifier = "resources"
  weight = 2

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  identifier = "contact"
  weight = 3

[[menu.main]]
  name = "Design"
  url = "/design/"
  identifier = "design"
  weight = 4

[[menu.main]]
  name = "Project Using Badger"
  url = "/project-using-badger/"
  identifier = "project-using-badger"
  weight = 5

[[menu.main]]
  name = "Frequently Asked Questions"
  url = "/faq/"
  identifier = "faq"
  weight = 6
